### ISSUE TITLE
Decode Pdu SMS Reference (ID) And SMS Status Report int

### ISSUE THREAD

**Issue by jeffersonsc** [webnice/pdu#2]
Hello, 
I'm using this lib for little project, in testing i noting two points, 
- First: in decoding PDU no contains sms id reference for me delete after decode.
`+CMGR: 1,,25\r\n07919740430900F302170B910000000000F0610130910435216101309104552100`
this is up exemple **1** is message reference.
- Second: in decode sms delivery report, the status of message in integer exemple: 00 equals message successful delivery at

**Comment by jeffersonsc** [comment]
i'm find tpMr return message reference.

**Comment by monoflash** [comment]
I find it difficult to answer anything. Documentation on the standard is extremely small, moreover, most likely there is no standard.
If you think that what's done by me contains an error, do a pull-request with the fixes.
