### ISSUE TITLE
Decode PDU Message refernece.

### ISSUE THREAD

**Issue by jeffersonsc** [webnice/pdu#3]
Hello,
what is the probability that in the decode of the pdu have the reference of the status of the delivery report?

**Comment by jeffersonsc** [comment]
i find tpMR in struct. and interface not return this value

**Comment by monoflash** [comment]
Messages about successful or not successful delivery are received and processed by the library. Try to send message with a confirmation and see for yourself.

**Comment by jeffersonsc** [comment]
Thanks for information, i'm using message confirmation request in send message.
In decoded messages of 3g modem , in message status conformation i do comparative id result of send with tpMr for math confirmation send.

**Comment by monoflash** [comment]
If you find some error in the library, do pull-request. Contributors are welcome.
