### ISSUE TITLE
No decode concatened message

### ISSUE THREAD

**Issue by jeffersonsc** [webnice/pdu#5]
Hi, i'm decode message long, 

str := \`+CMGL: 1,,159\r\n07919740430900F3440B910000000000F00008610130915483218C050003210301042F0020043F0440043E0434043E043B04360430044E002004410432043E04390020043F04430442044C002C000A042F0020043F0440043E0434043E043B04360430044E00200438043404420438002C000A041800200445043E0442044C0020043F043E0440043E044E00200441043204350440043D04430442044C000A0425043E0442044F\`

return result null

**Comment by monoflash** [comment]
Show the example completely, in the form of executable code. To be able to execute it.
Ideally, if you make an example in the form of a test for library.

**Comment by jeffersonsc** [comment]
`
package main

import (
	"log"
	"runtime"
	"time"

	pdu "gopkg.in/webnice/pdu.v1"
)

func main() {
	str := `+CMGL: 1,,159\r\n07919740430900F3440B910000000000F00008610130915483218C050003210301042F0020043F0440043E0434043E043B04360430044E002004410432043E04390020043F04430442044C002C000A042F0020043F0440043E0434043E043B04360430044E00200438043404420438002C000A041800200445043E0442044C0020043F043E0440043E044E00200441043204350440043D04430442044C000A0425043E0442044F`

	pduCoder := pdu.New().Decoder(messageReceiver)
	defer pduCoder.Done()

	pduCoder.Writer().Write([]byte(str))

	runtime.Gosched()
	runtime.GC()
	time.Sleep(3 * time.Second)
}

func messageReceiver(msg pdu.Message) {
	log.Println("msg ", msg)
}

`

**Comment by monoflash** [comment]
You took from the example the message code that can come from the modem, but did not pay attention to that in one message from the device can contain a fragment of one SMS.

SMS fragments accumulate in memory for a while (wait until the missing parts arrive) and only then return to the messageReceiver.

If time passes and SMS parts do not arrive, then such a message is returned with an error. The error can be read by calling msg.Error()

The function pduCoder.Done () is done just in end time to return from memory all the accumulated parts of incomplete messages.

**Comment by monoflash** [comment]
SMS one:
It's a complete SMS message: https://github.com/webnice/pdu/blob/v1/_example/example.go#L118-L119

SMS two
it's a first part of SMS: https://github.com/webnice/pdu/blob/v1/_example/example.go#L124-L125
it's a second part of SMS: https://github.com/webnice/pdu/blob/v1/_example/example.go#L120-L121
it's a last part of SMS: https://github.com/webnice/pdu/blob/v1/_example/example.go#L122-L123

In the example, this is done specifically to show and test the work of the library with chunks of messages that can come in a different order

**Comment by jeffersonsc** [comment]
I'm testing in a site https://smspdu.benjaminerhart.com/?pdu=0041000B915121551532F40000A0050003000301986F79B90D4AC3E7F53688FC66BFE5A0799A0E0AB7CB741668FC76CFCB637A995E9783C2E4343C3D4F8FD3EE33A8CC4ED359A079990C22BF41E5747DDE7E9341F4721BFE9683D2EE719A9C26D7DD74509D0E6287C56F791954A683C86FF65B5E06B5C36777181466A7E3F5B0AB4A0795DDE936284C06B5D3EE741B642FBBD3E1360B14AFA7E7

this message contains 3 concatened messages. 

in my code add msg.Error() and not response error.
```
func messageReceiver(msg pdu.Message) {

	if msg.Error() != nil {
		log.Println("Error: ", msg.Error().Error())
	}
	log.Println("msg ", msg)

}
```

**Comment by jeffersonsc** [comment]
Sorry my error, anderstend problem this message conains 9 parts this up example is 6 of 9 one fragment.

**Comment by monoflash** [comment]
You code:

1. `pdu "gopkg.in/webnice/pdu.v1"` No need to rename the library. Use: import "gopkg.in/webnice/pdu.v1"
2. \r\n and ``` ` ``` Please see the documentation for golang how to correctly use line breaks when using back quotes

I modify your code and upload to example folder.
Please look at this: https://github.com/webnice/pdu/blob/v1/_example/example2.go

**Comment by monoflash** [comment]
`> in my code add msg.Error() and not response error.`

I saw and repeated the situation of no error with an incorrect sms message.
Fixed this...

Thank you for helping me improve the library.

**Comment by jeffersonsc** [comment]
Hi, i'm testing concat message, when run is not finaly proccess e my cpu allocated in 100% one core down my code:

My real code [gist my code](https://gist.github.com/jeffersonsc/2deb1858e74691783af2726d7576318b)

My test code
```
package main

import (
	"bytes"
	"fmt"
	"log"
	"time"

	"gopkg.in/webnice/pdu.v1"
)

func main() {
	// var incomming = []string{
	// 	`+CMGR: 1,,159
	// 07919740430900F3440B910000000000F00008610130915483218C050003210302044200200441043E043C043D0435043D044C044F0020043C043E0438002C000A04180020043D0435002004340430044E04420020043C043D04350020043704300441043D04430442044C000A041E043F044F0442044C00200442044004350432043E04330438002004320020043D043E04470438002C000A042F00200437043D0430044E0020`,
	// 	`+CMGR: 1,,95
	// 07919740430900F3440B910000000000F00008610130915493214C05000321030320130020044D0442043E0020043C043E04390020043F04430442044C002C000A04180020043F0440043E0434043E043B04360430044E00200438043404420438002E002E002E`,
	// 	`+CMGR: 1,,159
	// 07919740430900F3440B910000000000F00008610130915483218C050003210301042F0020043F0440043E0434043E043B04360430044E002004410432043E04390020043F04430442044C002C000A042F0020043F0440043E0434043E043B04360430044E00200438043404420438002C000A041800200445043E0442044C0020043F043E0440043E044E00200441043204350440043D04430442044C000A0425043E0442044F`,
	// }

	// var incomming = []string{
	// 	`+CMGL: 0,1,,160\r\n0791551010010291640D91551199339980F40008811011905404888C050003E10401005400650073007400650020006400650020006E006F0076006F0020007000610072006100200076006F006300EA002000650020007300750061002000660061006D00ED006C0069006100200065002000720065006C006100630069006F006E0061006D0065006E0074006F007300200064006F0020006E006F00200062007200650061006B`,
	// 	`+CMGL: 1,1,,160\r\n0791551010010291600D91551199339980F40008811011905404888C050003E10403006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064`,
	// 	`+CMGL: 2,1,,160\r\n0791551010010291640D91551199339980F40008811011905404888C050003E10402002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061`,
	// 	`+CMGL: 3,0,,160\r\n0791551010010291640D91551199339980F40008811011906414888C050003E10403006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064`,
	// }

	incomming := []string{
		"+CMGL: 0,1,,160\r\n0791551010010291640D91551199339980F40008811011905404888C050003E10401005400650073007400650020006400650020006E006F0076006F0020007000610072006100200076006F006300EA002000650020007300750061002000660061006D00ED006C0069006100200065002000720065006C006100630069006F006E0061006D0065006E0074006F007300200064006F0020006E006F00200062007200650061006B",
		"+CMGL: 1,1,,160\r\n0791551010010291600D91551199339980F40008811011905404888C050003E10403006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064",
		"+CMGL: 2,1,,160\r\n0791551010010291640D91551199339980F40008811011905404888C050003E10402002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061",
		"+CMGL: 3,1,,160\r\n0791551010010291640D91551199339980F40008811011906414888C050003E10403006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064006F002000700061007200610020006F002000640069006100200074006F0064006F002000650020007100750061006C00710075006500720020006400FA00760069006400610020006500730074006F007500200069006E0064",
		"+CMGL: 4,0,,42\r\n0791551010010291640D91551199339980F400088110119064248816050003E10404006F002000700061007200610020006F",
		"+CMGL: 5,0,,42\r\n0791551010010291640D91551199339980F400088110119074948816050003E10404006F002000700061007200610020006F",
	}
	pduCoder := pdu.New().Decoder(messageReceiver)
	for _, s := range incomming {
		pduCoder.Writer().Write([]byte(s))
	}

	pduCoder.Done()

	time.Sleep(time.Second * 1)
}

func messageReceiver(msg pdu.Message) {
	var out *bytes.Buffer

	out = &bytes.Buffer{}
	defer log.Println(out)

	fmt.Fprintln(out, "New message found")
	if msg.Error() != nil {
		fmt.Fprintf(out, " * Type: %s\n", msg.Type())
		fmt.Fprintf(out, " * Message error: %s\n", msg.Error())
		return
	}

	fmt.Fprintf(out, " * SMSC: %s", msg.ServiceCentreAddress())
	if msg.Type() == pdu.TypeSmsStatusReport {
		fmt.Fprintf(out, " (status report: [%s] %s)", msg.DischargeTime(), msg.ReportStatus())
	}
	fmt.Fprintln(out, "")

	fmt.Fprintf(out, " * From: %s\n", msg.OriginatingAddress())
	fmt.Fprintf(out, " * Type: %s\n", msg.Type())
	fmt.Fprintf(out, " * SMS (%d): %s\n", msg.DataParts(), msg.Data())
}
```

**Comment by jeffersonsc** [comment]
For information, I added time sleep of 120 seconds between receivers, this method resvolved my problem with contatenation message. sorry me for that.

**Comment by monoflash** [comment]
Yes, I tested your code above, it works, all SMSs are decoded.

Maybe I can help you, I have a ready project that works with a modem based on this library. I can give it to you whole and you'll see how to work with the modem and port correctly.

In your code, I noticed that you like to use time.Slep, it's a bad practice, you need to use channels and blocking on channels.

I have emailed you a link to the archive with the project.
